### ISSUE TITLE
ServerRequestContext.currentRequest() not working in reactive flow

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#1228]
This branch contains a test `io.micronaut.security.utils.serverrequestcontextspec.ServerRequestContextReactiveSpec` which reproduces the issue: 

https://github.com/micronaut-projects/micronaut-core/tree/issue-1228

The following code snippet reproduces the issue: 

```java
@Controller("/mycontroller")
class MyController {

    @Get
    Flowable<Message> index() {
        return Flowable.just("foo")
                .flatMapSingle(name -> {
                    if (ServerRequestContext.currentRequest().isPresent()) {
                        return Single.just(new Message("Sergio"));
                    }
                    return Single.just(new Message("Anonymous"));
                });
    }

    @Get("/simple")
    Flowable<Message> simple() {
        if (ServerRequestContext.currentRequest().isPresent()) {
            return Flowable.just(new Message("Sergio"));
        }
        return Flowable.just(new Message("Anonymous"));
    }
}
```

The  line ` if (ServerRequestContext.currentRequest().isPresent()) {` in the method `index()` returns false. Because it is not able to resolve the request. 

@goeh who pointed me to this issue has done a bit research. 

He has found a couple of interesting blog posts: 

[Thread Local Availability In Reactive Environments](https://kamilszymanski.github.io/thread-local-state-availability-in-reactive-services/)

It seems Reactor has a Context (https://projectreactor.io/docs/core/release/reference/#context) and it seems Spring Security 5 uses it to store authentication info during a reactive sequence.

**Comment by goeh** [comment]
The Reactor link above explains the problem very well and I have positive experience with using their solution in Spring Security applications. Unfortunately there seems to be no context concept in Reactive Streams or RxJava2.

Currently in Micronaut I'm using the workaround explained in the reactor link, where I extract authentication and tenant information early in controller methods and then save that info in my custom context instance. This context instance is then passed to all functions in the reactive chain. It's not pretty but it works.

**Comment by jameskleeh** [comment]
This is one of the many reasons to avoid the static pattern. I vote to close the issue. If you need a part or all of the request, inject it into the controller method.

**Comment by sdelamo** [comment]
@jameskleeh the issue is represented in a controller because I wanted to create the simplest test possible which reproduces the issue. 

But this is an important issue. Features such as security token propagation, tenant id propagation or `SecurityService` need `ServerRequestContext.currentRequest()` to work.

**Comment by jameskleeh** [comment]
@sdelamo I'm aware there are use cases where this pattern is necessary to work and thus that is why it exists. For those cases the workaround that was described previously could be used.

**Comment by graemerocher** [comment]
Resolved for RxJava, may need to open another issue for Reactor

**Comment by graemerocher** [comment]
Tested with Reactor seems to work already, probably our instrumentation for Reactor already handled that.

**Comment by goeh** [comment]
Many thanks @graemerocher I will test my services against the master branch this weekend and see how things work.

**Comment by goeh** [comment]
Sorry for commenting on a closed issue but I promised to give feedback once I had tested the fix.
I have good news. A can't trigger the problem anymore. The access token is propagated as it should everywhere. I removed lots of old workaround code today which resulted in much cleaner code. Thanks!

**Comment by denis111** [comment]
I tried io.micronaut.reactor:micronaut-reactor with latest stable Micronaut (v2.5.5 at the moment) and the issue seems not resolved. It works fine with RxJava.

**Comment by jameskleeh** [comment]
@denis111 Please open an issue with an example project and steps to reproduce

**Comment by denis111** [comment]
@jameskleeh 
Thanks for the answer. I just discovered that it happens only when there's some .fromFuture() call in Mono/Flux flow. When there's only normal Mono/Flux creations like just/map/flatMap it doesn't happen. With Flowable there's no such problem. I'll create an issue.
