### ISSUE TITLE
Issue compiling class that uses recursive generic type definitions

### ISSUE THREAD

**Issue by knyttl** [micronaut-projects/micronaut-core#1607]
### Steps to Reproduce

1. Have following code on the classpath:

```
import java.util.*
import javax.persistence.*

@Entity
class Event : Item<Event>()

@MappedSuperclass
abstract class Item<T : Item<T>> {

    var id: Long? = null

    var revisions: MutableList<T> = ArrayList()
}
```

2. Run gradle build in Micronaut project.
3. You will get this exception:

https://gist.github.com/knyttl/4b34326939184910e93e7e4b3c03012b

### Expected Behaviour

1. The exception should be more informative to be able to find out what causes the problem.
2. Gradle build should not fail.

### Actual Behaviour

1. We get StackOverflow error with not enough information.
2. Gradle build fails.

### Environment Information

- **Operating System**: Any
- **Micronaut Version:** 1.1.0
- **JDK Version:** JDK 11

**Comment by graemerocher** [comment]
Seems a bug with recursive generics

**Comment by knyttl** [comment]
Do you need anything else from me? Do you have an estimate? Thanks very much.

**Comment by graemerocher** [comment]
Will look into this shortly, thanks for the report

**Comment by graemerocher** [comment]
I believe this has been fixed in in the 1.1.x branch and master by an earlier commit since I cannot reproduce

**Comment by graemerocher** [comment]
If you wish to verify the fix you can do so by adding the snapshot repo to `build.gradle`:

```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.1.0.BUILD-SNAPSHOT'
    }
}
```

**Comment by knyttl** [comment]
Thanks

**Comment by knyttl** [comment]
Unfortunately, the issue persist event with the BUILD-SNAPSHOT version.

The sources are here:

https://gitlab.com/GoOutPublic/MicronautKotlinDemo/tree/stackoverflow

With the entity here:

https://gitlab.com/GoOutPublic/MicronautKotlinDemo/blob/stackoverflow/src/main/kotlin/net/goout/micronaut/Entity.kt

And the CI build and fail:

https://gitlab.com/GoOutPublic/MicronautKotlinDemo/-/jobs/207179270

**Comment by knyttl** [comment]
I cannot reopen the issue, will you please do?

**Comment by graemerocher** [comment]
Problem seems to be specific to Kotlin, equivalent Java code works fine.

**Comment by knyttl** [comment]
I still thing the logs could be imporved as well :-)

**Comment by graemerocher** [comment]
The reason you were still seeing the error was `micronautVersion` was set to `1.1.0.BUILD-SNAPSHOT` instead of the current snapshot which is `1.1.1.BUILD-SNAPSHOT`

However, with that version I get this exception:

```
Run the build with '--info' for more details.
e: error: Error finalizing type visitor [io.micronaut.inject.beans.visitor.IntrospectedTypeElementVisitor@5ab34e2b]: null
e: error: cannot access $Event$Introspection
  bad class file: /Users/graemerocher/dev/micronaut/apps/MicronautKotlinDemo/build/tmp/kapt3/classes/main/net/goout/micronaut/$Event$Introspection.class
    class file contains wrong class: net.goout.micronaut.$Event$IntrospectionRef$$AnnotationMetadata
    Please remove or make sure it appears in the correct subdirectory of the classpath.
e: java.lang.IllegalStateException: failed to analyze: java.lang.NullPointerException
        at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:128)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:131)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:103)
        a
```

As for improving the logs, it is often down to the quality of the compiler implementation and currently Kotlin is significantly worse than Java when it comes to compiler errors, which is unfortunate.

**Comment by graemerocher** [comment]
Finally got to the bottom of it and pushed a fix, will be resolved in the next published snapshot when the build completes

**Comment by knyttl** [comment]
Thanks, lovely!
