### ISSUE TITLE
Properly implement synthetic bridge methods

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#4447]
The problem is explained here:

https://github.com/micronaut-projects/micronaut-data/issues/669#issuecomment-723488254

And introduced by the fix for https://github.com/micronaut-projects/micronaut-core/issues/4236

### Example Application

https://github.com/issmo/overriden-methods

**Comment by jameskleeh** [comment]
@graemerocher The test in the example app fails in 2.0.3 and the fix for #4236 was not introduced until 2.1.1 so I don't think its relevant

**Comment by graemerocher** [comment]
Ok, eitherway there is a regression somewhere, the issue is here so it doesn't get forgotten

**Comment by issmo** [comment]
@jameskleeh in 2.0.3 this was introduced by the fix for #3892. If possible, could you please explain the rationale behind adding the return type of a method to the "processed" cache key.  It looks like we are going back and forth between removing the return type from the key to solve some issues and adding it back to solve others.

I might be mistaken as I'm not an expert in micronaut code, but to me, Java prohibits implementing a method with the same name and parameters regardless of the return type as the runtime cannot decide between which method to call. This should favour a caching key without the return type and more generally, preventing the framework from implementing a method with the same signature twice. I think this is key here, as we might have different annotation processors trying to implement the same method (maybe this is already prevented by the annotation processor, is it?)  

On the other side, is there any cases where we would need to hand all overriden methods to the annotation processors? only to some of them?
 
If this is the case, we should have:
1.  A way to somehow prioritize the final implementation to retain among the different "conflicting" processors implementing the same method.
2. Maybe hand off caching and ignoring processed method to the sub classes of SuperclassAwareTypeVisitor

does this make sense?

**Comment by jameskleeh** [comment]
@issmo That makes sense but that isn't how the JDK produces bytecode. It does allow for 2 methods with the same signature but different return types.

In the CategoryAnswerRepository intercepted class there are 2 methods, and Groovy is choosing to execute the one that returns an Iterable and does not have the `@Join` annotation.

```
    public List findAll() {
        ExecutableMethod var1 = this.$proxyMethods[0];
        Interceptor[] var2 = this.$interceptors[0];
        MethodInterceptorChain var3 = new MethodInterceptorChain(var2, this, var1, new Object[0]);
        return (List)var3.proceed();
    }
    public Iterable findAll() {
        ExecutableMethod var1 = this.$proxyMethods[7];
        Interceptor[] var2 = this.$interceptors[7];
        MethodInterceptorChain var3 = new MethodInterceptorChain(var2, this, var1, new Object[0]);
        return (Iterable)var3.proceed();
    }
```

The JVM generates something like this:

```
  // access flags 0x401
  // signature ()Ljava/util/List<Lio/micronaut/data/issues/entities/CategoryAnswer;>;
  // declaration: java.util.List<io.micronaut.data.issues.entities.CategoryAnswer> findAll()
  public abstract findAll()Ljava/util/List;
  @Lio/micronaut/data/annotation/Join;(value="votes")

  // access flags 0x1041
  public synthetic bridge findAll()Ljava/lang/Iterable;
  @Lio/micronaut/data/annotation/Join;(value="votes")
   L0
    LINENUMBER 13 L0
    ALOAD 0
    INVOKEVIRTUAL io/micronaut/data/issues/repositories/CategoryAnswerRepository.findAll ()Ljava/util/List;
    ARETURN
   L1
    LOCALVARIABLE this Lio/micronaut/data/issues/repositories/CategoryAnswerRepository; L0 L1 0
    MAXSTACK = 1
    MAXLOCALS = 1
}
```

As you can see it simply delegates to the other `findAll` method and casts the returned value to `List`. It also retains the annotation metadata of the other `findAll` method. The correct fix is to change our method to be more like how the JDK does it.

**Comment by issmo** [comment]
@jameskleeh I do agree on the observation on the bytecode side with the synthetic bridge on CategoryAnswerRepository. However, please bear in mind that this is done as a part of the type erasure process by the compiler.

And I think that it is not wrong to implement only the top method without synthetic bridge and this will favour simplicity in the implementation.

The type erasure and synthetic bridges are already implemented by the compiler on the class micronaut extends, in this case CategoryAnswerRepository. This ensures that all the possible flavours of the method being implemented (in this particular example List<CategoryAnswer> findAll() and Iterable<CategoryAnswer> findAll()) are all overriding/hiding super class implementations and redirected by their synthetic methods to the the method being implemented (List findAll()). Thus, all is needed is to override this method (which is abstract) by implementing it in the CategoryAnswerRepository$Intercepted class. 

This reasoning only holds because the CategoryAnswerRepository$Intercepted is a synthetic class and is never directly referenced and no additional polymorphism is happening, otherwise I do agree with you that we should implement synthetic methods too. This will greatly simplify the implementation and the fix for this issue.

Let me know if I am missing some use cases.

**Comment by dstepanov** [comment]
I was trying to take a look at it but it looks like it's working in 2.2.0.BUILD-SNAPSHOT. Maybe it was fixed by https://github.com/micronaut-projects/micronaut-core/pull/4204

**Comment by graemerocher** [comment]
@issmo can you verify your issue is fixed with 2.2.0?

**Comment by issmo** [comment]
@graemerocher the issue related to multiple implementations of the same methods is fixed in 2.2.0

**Comment by jameskleeh** [comment]
The only explanation I can give for this specific issue to be working in 2.2.0 is the upgrade in Groovy from 3.0.4 to 3.0.5

**Comment by issmo** [comment]
@jameskleeh this looks like the only explanation as the generated Intercepted repository classes do still have the overrides implemented multiple times. Looks like Groovy is now picking the correct method in my test case...

**Comment by graemerocher** [comment]
Thanks for confirming
