### ISSUE TITLE
Add a check in NettyFileUploadInputStream.close() to prevent it from throwing "io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1" if the stream is closed more than once

### ISSUE THREAD

**Issue by rohit-s8** [micronaut-projects/micronaut-core#5973]
### Expected Behavior

My application receives a file through multipart upload. I use CompletedFileUpload for this purpose. The file then needs to be saved to OCI Object Store using oci-java-sdk-objectstorage. The process is basically as follows:
```java
public class ServiceClass {
  
  private final ObjectStorage os;
  ...
  ...
  ...

  private void uploadFile(CompletedFileUpload file) throws IOException {
    String namespace = ...
    String bucket = ....
    String name = file.getFilename();  
    PutObjectRequest request = PutObjectRequest.builder()
        .namespaceName(namespace)
        .bucketName(bucket)
        .objectName(name)
        .putObjectBody(file.getInputStream())
        .build();
     os.putObject(request);
  }
}
```
There's nothing exceptional happening here and so I expected it to upload the file without any errors.

### Actual Behaviour

However, as mentioned in the title, when the function `uploadFile` is called, the exception `IllegalReferenceCountException` is thrown:
```
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:74)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:138)
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76)
	at io.micronaut.http.server.netty.multipart.NettyFileUploadInputStream.close(NettyFileUploadInputStream.java:55)
	at com.oracle.bmc.io.internal.KeepOpenInputStream.closeStream(KeepOpenInputStream.java:55)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.putObject(ObjectStorageClient.java:1651)
        .
        .
```
More specifically it throws an exception at the line where `os.putObject()` is called.

My multipart configuration properties are as follows:
```yaml
micronaut:
  server:
    multipart:
      enabled: true
      max-file-size: 20MB
      disk: true
```

### Environment Information

```
❯ mvn -v
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 11.0.4, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.4.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

### Version

2.4.0

**Comment by rohit-s8** [comment]
After following the stack trace, I found out the reason for the exception:
Essentially the `ObjectStorageClient.putObject()` is invoking `io.micronaut.http.server.netty.multipart.NettyFileUploadInputStream.close` **twice** within the same invocation.

The first time it's called during the invocation https://github.com/oracle/oci-java-sdk/blob/623c82f32f99de9f60a7009d3fcf412cf0b94c12/bmc-objectstorage/bmc-objectstorage-generated/src/main/java/com/oracle/bmc/objectstorage/ObjectStorageClient.java#L1628
which actually calls `NettyFileUploadInputStream.close()` in the following line https://github.com/eclipse-ee4j/jersey/blob/52c8aa4d57f35ae2f93b81225cf271864e7a91cd/core-common/src/main/java/org/glassfish/jersey/message/internal/InputStreamProvider.java#L84

The second time is essentially within the `ObjectStorageClient.putObject()` itself at the line https://github.com/oracle/oci-java-sdk/blob/623c82f32f99de9f60a7009d3fcf412cf0b94c12/bmc-objectstorage/bmc-objectstorage-generated/src/main/java/com/oracle/bmc/objectstorage/ObjectStorageClient.java#L1651

The reason for the exception is the following:
```java
    @Override
    public void close() throws IOException {
        super.close();
        if (releaseOnClose) {
            // exception thrown here during the second invocation to close
            file.release();
        }
    }
```
`NettyFileUploadInputStream.close()` invokes `io.netty.handler.codec.http.multipart.FileUpload.release()` which throws the exception "io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1", when `NettyFileUploadInputStream.close()` is invoked the second time as the file has already been _released_.

The fix here is simple. Modify the `NettyFileUploadInputStream.close()` as follows:
```java
    @Override
    public void close() throws IOException {
        super.close();
        if (releaseOnClose && file.refCnt() != 0) { // check if the file has not already been released
            file.release();
        }
    }
```
This way, it won't try to _release_ an already _released_ file.

**Comment by dstepanov** [comment]
I think the problem is already fixed in the latest version. Can you please try version 2.5.12?

**Comment by rohit-s8** [comment]
Hmmm, the code looks exactly the same to me: https://github.com/micronaut-projects/micronaut-core/blob/v2.5.12/http-server-netty/src/main/java/io/micronaut/http/server/netty/multipart/NettyFileUploadInputStream.java

Or has the fix been implemented elsewhere? I guess i'll give it a try

**Comment by dstepanov** [comment]
There were some Netty bugs...

**Comment by rohit-s8** [comment]
Tried 2.5.12, but with no success. Still getting the same exception at the exact same point.

I don't think this is a netty bug. The problem lies in the current implementation of `io.micronaut.http.server.netty.multipart.NettyFileUploadInputStream.close()`. There needs to be an explicit check to see whether the file has already been released before invoking `io.netty.handler.codec.http.multipart.FileUpload.release()`

**Comment by jameskleeh** [comment]
I don't think this is a bug or an issue on our side. The stream shouldn't be closed multiple times because that doesn't make sense. You could say its an improvement to make it more resilient to incorrect usage of the stream

**Comment by jameskleeh** [comment]
I think I actually disagree with my previous comment. The javadoc for Closeable, which we are overriding in this case says `If the stream is already closed then invoking this method has no effect.`. It doesn't say that in the javadoc for the override in `InputStream`, which provides an empty implementation but I think it's intended the behavior should still apply.
