### ISSUE TITLE
POST under h2c returns 413 Request Entity Too Large

### ISSUE THREAD

**Issue by cbeams** [micronaut-projects/micronaut-core#6299]
### Expected Behavior

The following is taken from a commit that will be linked to this issue shortly after its creation:

    This commit sets Micronaut's http-version to 1.1, such that the
    following steps work as expected:

    1. Run the application

        ./gradlew run

    2. Run

        curl -v -H "Content-Type: application/json" :2040/peers \
          --data '{"address":"http://localhost:2041"}'

    3. Notice that the response is 201 Created as expected.

### Actual Behaviour

The following is taken from a commit that will be linked to this issue shortly after its creation:

    This commit sets Micronaut's http-version to 2.0, in order to reproduce
    the reported issue.

    Repro steps when requesting with HTTP/1.1:

    1. Run the application:

        ./gradlew run

    2. Run the following (note that we are *not* passing `--http2` here):

        curl -v -H "Content-Type: application/json" :2040/peers \
          --data '{"address":"http://localhost:2041"}'

    3. Notice that the response hangs indefinitely

    Repro steps when requesting an HTTP/2 upgrade

    1. Reuse the same application already running from the steps above.

    2. Run the following (note that we *are* passing `--http2` this time):

        curl -v --http2 -H "Content-Type: application/json" :2040/peers \
          --data '{"address":"http://localhost:2041"}'

    3. Notice that the response comes back 413 Request Entity Too Large

### Steps To Reproduce

See above.

### Environment Information

JDK 16

### Example Application

https://github.com/cbeams/xnd

### Version

3.1.0-SNAPSHOT

**Comment by cbeams** [comment]
See the commits linked above:

- https://github.com/cbeams/xnd/commit/84ba65cf460c9e1ca1bab99340f6722678687e37
- https://github.com/cbeams/xnd/commit/4f00a06dee0762b5f96a59d7d3e6a891832caf7f

@jameskleeh and @graemerocher already have access to this repository.

**Comment by graemerocher** [comment]
@cbeams can you invite @yawkat

**Comment by graemerocher** [comment]
Think this may be addressed with https://github.com/micronaut-projects/micronaut-core/pull/6300

**Comment by cbeams** [comment]
Done!

**Comment by yawkat** [comment]
Yes the first issue is likely fixed by #6300. The "request entity too large" error isn't, will take a look.

**Comment by cbeams** [comment]
Just to confirm, the first issue is indeed fixed by #6300. I just tested it out against the latest snapshot. And the second, 'entity too large' issue persists as predicted.

**Comment by yawkat** [comment]
The cause of this is very simple: we don't pass a `maxContentLength` to `HttpServerUpgradeHandler`, so it defaults to 0, and refuses to accept any content for the initial HTTP upgrade request. 

 Unfortunately, `HttpServerUpgradeHandler` has to buffer the full message, and we won't be able to use the normal streaming mechanisms of the framework. This means we will need a separate configuration property for this max content length, and it should probably be lower than maxRequestSize. This will also lead to semantics of the first request being different, which is just a pain.

I will work on this after my vacation, but it seems to me like the solution will be less than ideal. It doesn't look like netty supports a good way to do this with their `HttpServerUpgradeHandler` (and I can see why it would be difficult for them). So my recommendation even with the fix will be to avoid putting potentially large amounts of data into the initial upgrade request.

**Comment by cbeams** [comment]
Thanks, @yawkat. I guess this awkwardness around handling upgrades is all the more reason to support and use prior h2(c) knowledge á la #6301.

**Comment by cbeams** [comment]
Thanks, @yawkat. Please see https://github.com/cbeams/xnd/commit/c3303e2e299a7ff827740ab6276698562d48ebdf, where I've attempted to upgrade to 3.2.0-SNAPSHOT to pick up this fix, but am still seeing problematic behavior with `--http2`.
