### ISSUE TITLE
Problems with provider TypeElementVisitorProcessor after migrating to micronaut 4

### ISSUE THREAD

**Issue by viniciusxyz** [micronaut-projects/micronaut-core#9570]
### Expected Behavior

When using rewrite in my multi-module project I was hoping that the upgrade from micronaut 3 to 4 would be successful and my application would work

### Actual Behaviour

After performing the update I get the exception below when trying to compile my project:

```sh
 Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider io.micronaut.annotation.processing.TypeElementVisitorProcessor could not be instantiated
```

### Steps To Reproduce

Honestly I can't say exactly how to reproduce it, I have a multi-module project (internal framework based on micronaut) with about 160 modules, and the application is created from it so it's hard to identify exactly where the problem is, I had a javax service .annotation.processing.Processor, but even removing it the problem continues

### Environment Information

- SO: Windows 11
- Java: Graalvm 17.0.7
- Maven 3.8.6

### Extra problem

A problem I would like to mention and know if I need to open another issue is that the rewrite is not making changes related to micronaut validation, thus the dependency:

```xml
<dependency>
    <groupId>io.micronaut</groupId>
   <artifactId>micronaut-validation</artifactId>
   <version>${micronaut.version}</version>
</dependency>
```

is not changed to:

```xml
<dependency>
    <groupId>io.micronaut.validation</groupId>
   <artifactId>micronaut-validation</artifactId>
   <version>${micronaut.version}</version>
</dependency>
```

And the package `javax.validation` is not changed to `jakarta.validation`

### Version

4.0.0

**Comment by graemerocher** [comment]
We will look into it. Thanks

**Comment by sdelamo** [comment]
We are improving the OpenRewrite recipe for Maven and we will release a version soon.

 @jeremyg484 can you update @viniciusxyz ?

**Comment by viniciusxyz** [comment]
@sdelamo I opened an issue to handle the problem with the TypeElementVisitorProcessor and pointed out this extra point of the recipe, do you prefer that I open a separate issue for the openrewrite recipe to better organize it?

**Comment by jeremyg484** [comment]
@viniciusxyz The Micronaut Validation configuration problem has definitely been fixed in the patch version of rewrite-micronaut that we are getting ready to release, and we've fixed several other bugs with Maven builds as well. I *think* the error you are seeing should go away because of some of these fixes (some of which are related to annotation processor configuration), but it is hard to say for sure without seeing the exact changes that the recipe made to your `pom.xml`.

Would you be able to share the changes that the recipe make to your `pom.xml` and/or what your `<annotationProcessorPaths>` configuration looks like after running the recipe?

**Comment by viniciusxyz** [comment]
@jeremyg484 unfortunately I can't :/ That's because as I said earlier it's not a microservice directly, but one that uses an internal framework based on micronaut and it's huge, so even if I could send it I don't think it would make much sense to you , I'm going to do the following, as soon as the next version comes out I'll test it and if the problem still persists I'll try to isolate and create a separate project where I can reproduce the problem, I haven't done that yet because it's something very laborious and I didn't have time.

**Comment by jeremyg484** [comment]
> @jeremyg484 unfortunately I can't :/ That's because as I said earlier it's not a microservice directly, but one that uses an internal framework based on micronaut and it's huge, so even if I could send it I don't think it would make much sense to you , I'm going to do the following, as soon as the next version comes out I'll test it and if the problem still persists I'll try to isolate and create a separate project where I can reproduce the problem, I haven't done that yet because it's something very laborious and I didn't have time.

@viniciusxyz Ok, no worries. I'm hoping to get the new version released today or tomorrow at the latest. I will ping you again here when it's available and you can try it out.

**Comment by jeremyg484** [comment]
@viniciusxyz rewrite-micronaut 2.1.1 has been released with a number of fixes specifically for Maven apps. If you could give it a try and lets us know if you have any better success, that would be great!

Note that I did encounter the same `TypeElementVisitorProcessor` error in my testing at one point, and the cause seemed to be the versions of the annotation processors not having been updated correctly. That is one of the things we've fixed in rewrite-micronaut.

https://github.com/openrewrite/rewrite-micronaut/releases/tag/v2.1.1

**Comment by viniciusxyz** [comment]
@jeremyg484 The problem persists, I'll try to analyze it in depth over the weekend and come back with my analysis. Meanwhile there is a small typo in the [rewrite doc](https://micronaut.io/2023/07/14/upgrade-to-micronaut-framework-4-with-openrewrite-and-maven/) where it mentions **COMPLETE REWRITE-MAVEN-PLUGIN CONFIGURATION** the rewrite-micronaut version is still 2.1.0 instead of 2.1.1, I tried to find the source of the document to correct and send an MR, but I couldn't find it :/ can you tell me where it is?

**Comment by viniciusxyz** [comment]
@jeremyg484 I thought a little and managed to isolate the problem, and to my disappointment I was the problem :/ In a past version of micronaut, micronaut-openapi presented some problems for my team and I had to rollback the version by setting it directly and I ended up forgetting about it, which is why it was in version 4.8.6 instead of 5.0.1 which is correct for this update. I'm really sorry for the time spent on this. I will close the issue.  Thanks to the whole team for the support.

**Comment by vishal-groww** [comment]
I am facing a similar issue after upgrading to Micronaut 4.3.7 using openrewrite.
We are using micronaut in a multi-module maven project


        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <micronaut.version>4.3.7</micronaut.version>
        <micronaut.data.version>3.5.0</micronaut.data.version>
        
Exception details        

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider io.micronaut.annotation.processing.TypeElementVisitorProcessor could not be instantiated
[INFO] 1 error

**Comment by vishal-groww** [comment]
Build was failing after the micronaut upgrade due to `artifacts could not be resolved: io.micronaut:micronaut-bom:pom:4.3.7 (absent):`

Then I followed instructions from https://micronaut-projects.github.io/micronaut-platform/4.3.7/guide/
and replaced io.micronaut:micronaut-bom:pom:4.3.7 with
(io.micronaut.platform:micronaut-platform) and the Micronaut Core BOM (io.micronaut:micronaut-core-bom).

The error 'javax.annotation.processing.Processor' started showing up after this

**Comment by jeremyg484** [comment]
@vishal-groww If you're having issues after running the OpenRewrite recipe, please do raise an issue at https://github.com/openrewrite/rewrite-micronaut with some additional info about your particular project structure. It could be something is getting missed by the recipe with the multi-module setup.
